package etude.bootstrap

import scala.xml.Elem

object Icons {
  lazy val adjust: Elem = <span class="glyphicon glyphicon-adjust"></span>
  lazy val alignCenter: Elem = <span class="glyphicon glyphicon-align-center"></span>
  lazy val alignJustify: Elem = <span class="glyphicon glyphicon-align-justify"></span>
  lazy val alignLeft: Elem = <span class="glyphicon glyphicon-align-left"></span>
  lazy val alignRight: Elem = <span class="glyphicon glyphicon-align-right"></span>
  lazy val arrowDown: Elem = <span class="glyphicon glyphicon-arrow-down"></span>
  lazy val arrowLeft: Elem = <span class="glyphicon glyphicon-arrow-left"></span>
  lazy val arrowRight: Elem = <span class="glyphicon glyphicon-arrow-right"></span>
  lazy val arrowUp: Elem = <span class="glyphicon glyphicon-arrow-up"></span>
  lazy val asterisk: Elem = <span class="glyphicon glyphicon-asterisk"></span>
  lazy val backward: Elem = <span class="glyphicon glyphicon-backward"></span>
  lazy val banCircle: Elem = <span class="glyphicon glyphicon-ban-circle"></span>
  lazy val barcode: Elem = <span class="glyphicon glyphicon-barcode"></span>
  lazy val bell: Elem = <span class="glyphicon glyphicon-bell"></span>
  lazy val bold: Elem = <span class="glyphicon glyphicon-bold"></span>
  lazy val book: Elem = <span class="glyphicon glyphicon-book"></span>
  lazy val bookmark: Elem = <span class="glyphicon glyphicon-bookmark"></span>
  lazy val briefcase: Elem = <span class="glyphicon glyphicon-briefcase"></span>
  lazy val bullhorn: Elem = <span class="glyphicon glyphicon-bullhorn"></span>
  lazy val calendar: Elem = <span class="glyphicon glyphicon-calendar"></span>
  lazy val camera: Elem = <span class="glyphicon glyphicon-camera"></span>
  lazy val certificate: Elem = <span class="glyphicon glyphicon-certificate"></span>
  lazy val check: Elem = <span class="glyphicon glyphicon-check"></span>
  lazy val chevronDown: Elem = <span class="glyphicon glyphicon-chevron-down"></span>
  lazy val chevronLeft: Elem = <span class="glyphicon glyphicon-chevron-left"></span>
  lazy val chevronRight: Elem = <span class="glyphicon glyphicon-chevron-right"></span>
  lazy val chevronUp: Elem = <span class="glyphicon glyphicon-chevron-up"></span>
  lazy val circleArrowDown: Elem = <span class="glyphicon glyphicon-circle-arrow-down"></span>
  lazy val circleArrowLeft: Elem = <span class="glyphicon glyphicon-circle-arrow-left"></span>
  lazy val circleArrowRight: Elem = <span class="glyphicon glyphicon-circle-arrow-right"></span>
  lazy val circleArrowUp: Elem = <span class="glyphicon glyphicon-circle-arrow-up"></span>
  lazy val cloud: Elem = <span class="glyphicon glyphicon-cloud"></span>
  lazy val cloudDownload: Elem = <span class="glyphicon glyphicon-cloud-download"></span>
  lazy val cloudUpload: Elem = <span class="glyphicon glyphicon-cloud-upload"></span>
  lazy val cog: Elem = <span class="glyphicon glyphicon-cog"></span>
  lazy val collapseDown: Elem = <span class="glyphicon glyphicon-collapse-down"></span>
  lazy val collapseUp: Elem = <span class="glyphicon glyphicon-collapse-up"></span>
  lazy val comment: Elem = <span class="glyphicon glyphicon-comment"></span>
  lazy val compressed: Elem = <span class="glyphicon glyphicon-compressed"></span>
  lazy val copyrightMark: Elem = <span class="glyphicon glyphicon-copyright-mark"></span>
  lazy val creditCard: Elem = <span class="glyphicon glyphicon-credit-card"></span>
  lazy val cutlery: Elem = <span class="glyphicon glyphicon-cutlery"></span>
  lazy val dashboard: Elem = <span class="glyphicon glyphicon-dashboard"></span>
  lazy val download: Elem = <span class="glyphicon glyphicon-download"></span>
  lazy val downloadAlt: Elem = <span class="glyphicon glyphicon-download-alt"></span>
  lazy val earphone: Elem = <span class="glyphicon glyphicon-earphone"></span>
  lazy val edit: Elem = <span class="glyphicon glyphicon-edit"></span>
  lazy val eject: Elem = <span class="glyphicon glyphicon-eject"></span>
  lazy val envelope: Elem = <span class="glyphicon glyphicon-envelope"></span>
  lazy val euro: Elem = <span class="glyphicon glyphicon-euro"></span>
  lazy val exclamationSign: Elem = <span class="glyphicon glyphicon-exclamation-sign"></span>
  lazy val expand: Elem = <span class="glyphicon glyphicon-expand"></span>
  lazy val export: Elem = <span class="glyphicon glyphicon-export"></span>
  lazy val eyeClose: Elem = <span class="glyphicon glyphicon-eye-close"></span>
  lazy val eyeOpen: Elem = <span class="glyphicon glyphicon-eye-open"></span>
  lazy val facetimeVideo: Elem = <span class="glyphicon glyphicon-facetime-video"></span>
  lazy val fastBackward: Elem = <span class="glyphicon glyphicon-fast-backward"></span>
  lazy val fastForward: Elem = <span class="glyphicon glyphicon-fast-forward"></span>
  lazy val file: Elem = <span class="glyphicon glyphicon-file"></span>
  lazy val film: Elem = <span class="glyphicon glyphicon-film"></span>
  lazy val filter: Elem = <span class="glyphicon glyphicon-filter"></span>
  lazy val fire: Elem = <span class="glyphicon glyphicon-fire"></span>
  lazy val flag: Elem = <span class="glyphicon glyphicon-flag"></span>
  lazy val flash: Elem = <span class="glyphicon glyphicon-flash"></span>
  lazy val floppyDisk: Elem = <span class="glyphicon glyphicon-floppy-disk"></span>
  lazy val floppyOpen: Elem = <span class="glyphicon glyphicon-floppy-open"></span>
  lazy val floppyRemove: Elem = <span class="glyphicon glyphicon-floppy-remove"></span>
  lazy val floppySave: Elem = <span class="glyphicon glyphicon-floppy-save"></span>
  lazy val floppySaved: Elem = <span class="glyphicon glyphicon-floppy-saved"></span>
  lazy val folderClose: Elem = <span class="glyphicon glyphicon-folder-close"></span>
  lazy val folderOpen: Elem = <span class="glyphicon glyphicon-folder-open"></span>
  lazy val font: Elem = <span class="glyphicon glyphicon-font"></span>
  lazy val forward: Elem = <span class="glyphicon glyphicon-forward"></span>
  lazy val fullscreen: Elem = <span class="glyphicon glyphicon-fullscreen"></span>
  lazy val gbp: Elem = <span class="glyphicon glyphicon-gbp"></span>
  lazy val gift: Elem = <span class="glyphicon glyphicon-gift"></span>
  lazy val glass: Elem = <span class="glyphicon glyphicon-glass"></span>
  lazy val globe: Elem = <span class="glyphicon glyphicon-globe"></span>
  lazy val handDown: Elem = <span class="glyphicon glyphicon-hand-down"></span>
  lazy val handLeft: Elem = <span class="glyphicon glyphicon-hand-left"></span>
  lazy val handRight: Elem = <span class="glyphicon glyphicon-hand-right"></span>
  lazy val handUp: Elem = <span class="glyphicon glyphicon-hand-up"></span>
  lazy val hdd: Elem = <span class="glyphicon glyphicon-hdd"></span>
  lazy val hdVideo: Elem = <span class="glyphicon glyphicon-hd-video"></span>
  lazy val header: Elem = <span class="glyphicon glyphicon-header"></span>
  lazy val headphones: Elem = <span class="glyphicon glyphicon-headphones"></span>
  lazy val heart: Elem = <span class="glyphicon glyphicon-heart"></span>
  lazy val heartEmpty: Elem = <span class="glyphicon glyphicon-heart-empty"></span>
  lazy val home: Elem = <span class="glyphicon glyphicon-home"></span>
  lazy val importIcon: Elem = <span class="glyphicon glyphicon-import"></span>
  lazy val inbox: Elem = <span class="glyphicon glyphicon-inbox"></span>
  lazy val indentLeft: Elem = <span class="glyphicon glyphicon-indent-left"></span>
  lazy val indentRight: Elem = <span class="glyphicon glyphicon-indent-right"></span>
  lazy val infoSign: Elem = <span class="glyphicon glyphicon-info-sign"></span>
  lazy val italic: Elem = <span class="glyphicon glyphicon-italic"></span>
  lazy val leaf: Elem = <span class="glyphicon glyphicon-leaf"></span>
  lazy val link: Elem = <span class="glyphicon glyphicon-link"></span>
  lazy val list: Elem = <span class="glyphicon glyphicon-list"></span>
  lazy val listAlt: Elem = <span class="glyphicon glyphicon-list-alt"></span>
  lazy val lock: Elem = <span class="glyphicon glyphicon-lock"></span>
  lazy val logIn: Elem = <span class="glyphicon glyphicon-log-in"></span>
  lazy val logOut: Elem = <span class="glyphicon glyphicon-log-out"></span>
  lazy val magnet: Elem = <span class="glyphicon glyphicon-magnet"></span>
  lazy val mapMarker: Elem = <span class="glyphicon glyphicon-map-marker"></span>
  lazy val minus: Elem = <span class="glyphicon glyphicon-minus"></span>
  lazy val minusSign: Elem = <span class="glyphicon glyphicon-minus-sign"></span>
  lazy val move: Elem = <span class="glyphicon glyphicon-move"></span>
  lazy val music: Elem = <span class="glyphicon glyphicon-music"></span>
  lazy val newWindow: Elem = <span class="glyphicon glyphicon-new-window"></span>
  lazy val off: Elem = <span class="glyphicon glyphicon-off"></span>
  lazy val ok: Elem = <span class="glyphicon glyphicon-ok"></span>
  lazy val okCircle: Elem = <span class="glyphicon glyphicon-ok-circle"></span>
  lazy val okSign: Elem = <span class="glyphicon glyphicon-ok-sign"></span>
  lazy val open: Elem = <span class="glyphicon glyphicon-open"></span>
  lazy val paperclip: Elem = <span class="glyphicon glyphicon-paperclip"></span>
  lazy val pause: Elem = <span class="glyphicon glyphicon-pause"></span>
  lazy val pencil: Elem = <span class="glyphicon glyphicon-pencil"></span>
  lazy val phone: Elem = <span class="glyphicon glyphicon-phone"></span>
  lazy val phoneAlt: Elem = <span class="glyphicon glyphicon-phone-alt"></span>
  lazy val picture: Elem = <span class="glyphicon glyphicon-picture"></span>
  lazy val plane: Elem = <span class="glyphicon glyphicon-plane"></span>
  lazy val play: Elem = <span class="glyphicon glyphicon-play"></span>
  lazy val playCircle: Elem = <span class="glyphicon glyphicon-play-circle"></span>
  lazy val plus: Elem = <span class="glyphicon glyphicon-plus"></span>
  lazy val plusSign: Elem = <span class="glyphicon glyphicon-plus-sign"></span>
  lazy val print: Elem = <span class="glyphicon glyphicon-print"></span>
  lazy val pushpin: Elem = <span class="glyphicon glyphicon-pushpin"></span>
  lazy val qrcode: Elem = <span class="glyphicon glyphicon-qrcode"></span>
  lazy val questionSign: Elem = <span class="glyphicon glyphicon-question-sign"></span>
  lazy val random: Elem = <span class="glyphicon glyphicon-random"></span>
  lazy val record: Elem = <span class="glyphicon glyphicon-record"></span>
  lazy val refresh: Elem = <span class="glyphicon glyphicon-refresh"></span>
  lazy val registrationMark: Elem = <span class="glyphicon glyphicon-registration-mark"></span>
  lazy val remove: Elem = <span class="glyphicon glyphicon-remove"></span>
  lazy val removeCircle: Elem = <span class="glyphicon glyphicon-remove-circle"></span>
  lazy val removeSign: Elem = <span class="glyphicon glyphicon-remove-sign"></span>
  lazy val repeat: Elem = <span class="glyphicon glyphicon-repeat"></span>
  lazy val resizeFull: Elem = <span class="glyphicon glyphicon-resize-full"></span>
  lazy val resizeHorizontal: Elem = <span class="glyphicon glyphicon-resize-horizontal"></span>
  lazy val resizeSmall: Elem = <span class="glyphicon glyphicon-resize-small"></span>
  lazy val resizeVertical: Elem = <span class="glyphicon glyphicon-resize-vertical"></span>
  lazy val retweet: Elem = <span class="glyphicon glyphicon-retweet"></span>
  lazy val road: Elem = <span class="glyphicon glyphicon-road"></span>
  lazy val save: Elem = <span class="glyphicon glyphicon-save"></span>
  lazy val saved: Elem = <span class="glyphicon glyphicon-saved"></span>
  lazy val screenshot: Elem = <span class="glyphicon glyphicon-screenshot"></span>
  lazy val sdVideo: Elem = <span class="glyphicon glyphicon-sd-video"></span>
  lazy val search: Elem = <span class="glyphicon glyphicon-search"></span>
  lazy val send: Elem = <span class="glyphicon glyphicon-send"></span>
  lazy val share: Elem = <span class="glyphicon glyphicon-share"></span>
  lazy val shareAlt: Elem = <span class="glyphicon glyphicon-share-alt"></span>
  lazy val shoppingCart: Elem = <span class="glyphicon glyphicon-shopping-cart"></span>
  lazy val signal: Elem = <span class="glyphicon glyphicon-signal"></span>
  lazy val sort: Elem = <span class="glyphicon glyphicon-sort"></span>
  lazy val sortByAlphabet: Elem = <span class="glyphicon glyphicon-sort-by-alphabet"></span>
  lazy val sortByAlphabetAlt: Elem = <span class="glyphicon glyphicon-sort-by-alphabet-alt"></span>
  lazy val sortByAttributes: Elem = <span class="glyphicon glyphicon-sort-by-attributes"></span>
  lazy val sortByAttributesAlt: Elem = <span class="glyphicon glyphicon-sort-by-attributes-alt"></span>
  lazy val sortByOrder: Elem = <span class="glyphicon glyphicon-sort-by-order"></span>
  lazy val sortByOrderAlt: Elem = <span class="glyphicon glyphicon-sort-by-order-alt"></span>
  lazy val sound5_1: Elem = <span class="glyphicon glyphicon-sound-5-1"></span>
  lazy val sound6_1: Elem = <span class="glyphicon glyphicon-sound-6-1"></span>
  lazy val sound7_1: Elem = <span class="glyphicon glyphicon-sound-7-1"></span>
  lazy val soundDolby: Elem = <span class="glyphicon glyphicon-sound-dolby"></span>
  lazy val soundStereo: Elem = <span class="glyphicon glyphicon-sound-stereo"></span>
  lazy val star: Elem = <span class="glyphicon glyphicon-star"></span>
  lazy val starEmpty: Elem = <span class="glyphicon glyphicon-star-empty"></span>
  lazy val stats: Elem = <span class="glyphicon glyphicon-stats"></span>
  lazy val stepBackward: Elem = <span class="glyphicon glyphicon-step-backward"></span>
  lazy val stepForward: Elem = <span class="glyphicon glyphicon-step-forward"></span>
  lazy val stop: Elem = <span class="glyphicon glyphicon-stop"></span>
  lazy val subtitles: Elem = <span class="glyphicon glyphicon-subtitles"></span>
  lazy val tag: Elem = <span class="glyphicon glyphicon-tag"></span>
  lazy val tags: Elem = <span class="glyphicon glyphicon-tags"></span>
  lazy val tasks: Elem = <span class="glyphicon glyphicon-tasks"></span>
  lazy val textHeight: Elem = <span class="glyphicon glyphicon-text-height"></span>
  lazy val textWidth: Elem = <span class="glyphicon glyphicon-text-width"></span>
  lazy val th: Elem = <span class="glyphicon glyphicon-th"></span>
  lazy val thLarge: Elem = <span class="glyphicon glyphicon-th-large"></span>
  lazy val thList: Elem = <span class="glyphicon glyphicon-th-list"></span>
  lazy val thumbsDown: Elem = <span class="glyphicon glyphicon-thumbs-down"></span>
  lazy val thumbsUp: Elem = <span class="glyphicon glyphicon-thumbs-up"></span>
  lazy val time: Elem = <span class="glyphicon glyphicon-time"></span>
  lazy val tint: Elem = <span class="glyphicon glyphicon-tint"></span>
  lazy val tower: Elem = <span class="glyphicon glyphicon-tower"></span>
  lazy val transfer: Elem = <span class="glyphicon glyphicon-transfer"></span>
  lazy val trash: Elem = <span class="glyphicon glyphicon-trash"></span>
  lazy val treeConifer: Elem = <span class="glyphicon glyphicon-tree-conifer"></span>
  lazy val treeDeciduous: Elem = <span class="glyphicon glyphicon-tree-deciduous"></span>
  lazy val unchecked: Elem = <span class="glyphicon glyphicon-unchecked"></span>
  lazy val upload: Elem = <span class="glyphicon glyphicon-upload"></span>
  lazy val usd: Elem = <span class="glyphicon glyphicon-usd"></span>
  lazy val user: Elem = <span class="glyphicon glyphicon-user"></span>
  lazy val volumeDown: Elem = <span class="glyphicon glyphicon-volume-down"></span>
  lazy val volumeOff: Elem = <span class="glyphicon glyphicon-volume-off"></span>
  lazy val volumeUp: Elem = <span class="glyphicon glyphicon-volume-up"></span>
  lazy val warningSign: Elem = <span class="glyphicon glyphicon-warning-sign"></span>
  lazy val wrench: Elem = <span class="glyphicon glyphicon-wrench"></span>
  lazy val zoomIn: Elem = <span class="glyphicon glyphicon-zoom-in"></span>
  lazy val zoomOut: Elem = <span class="glyphicon glyphicon-zoom-out"></span>
}
